baseURL = "http://magnesium.coop/"
languageCode = "en-us"
#title = "Magnesium"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Magnesium"
    #description = "Personal blog theme powered by Hugo"
    githubUsername = "#mgcoders"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    css = ["css/custom.css"]

#[[menu.main]]
#    url = "/"
#    name = "Home"
#    weight = 1
#
#[[menu.main]]
#    url = "/post/"
#    name = "Posts"
#    weight = 2
#
#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:info@magnesium.coop"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/MgCoders/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/magnesiumcoop/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/company/magnesium-coders"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.facebook.com/mgcoders/"
    name = "facebook"
    weight = 5
